version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Zipping app..."
      - zip -r static-gym-html-css-app.zip ./*
artifacts:
  files:
    - static-gym-html-css-app.zip
